Lesson1 task1
aandrewkaa/KotlinSprint pull request #1
Opened 2023-06-26 01:13 UTC by aandrewkaa

2023-06-26 18:00 UTC, ievetrov requested changes
Привет! отличное оформление пулл реквеста, все корректно

по коду оставил пару комментариев. исправь плиз и сделай коммит в эту же ветку. изменения подтянутся в этот пулл реквест.

не забудь для внесения изменений переключаться в соответствующую ветку

когда все будет готово - ссылку на этот же пулл реквест присылай в бот к соответствующей отклоненной задаче

2023-06-26 18:00 UTC, ievetrov commented on src/main/kotlin/lesson1/lesson1_task1.kt
> +    var number_of_orders: UShort = 75U //var т.к. количество заказов меняется
в Котлин переменные принято именовать стилем camelCase. в твоей реализации используется snake_case

2023-06-26 18:00 UTC, ievetrov commented on src/main/kotlin/lesson1/lesson1_task1.kt
> +    println("Это решение задачи из 1 из урока 1 ")
это можно убрать, к условию отношения не имеет (в видео для примера)

2023-06-26 22:29 UTC, aandrewkaa commented on src/main/kotlin/lesson1/lesson1_task1.kt
> +    println("Это решение задачи из 1 из урока 1 ")
убрал

2023-06-26 22:29 UTC, aandrewkaa commented on src/main/kotlin/lesson1/lesson1_task1.kt
> +    var number_of_orders: UShort = 75U //var т.к. количество заказов меняется
стиль заменил

2023-06-27 12:29 UTC, ievetrov approved these changes
все ок, можно мержить в мастер

2023-06-27 22:03 UTC, merged