KS-3-1
aandrewkaa/KotlinSprint pull request #12
Opened 2023-06-28 23:38 UTC by aandrewkaa

2023-06-29 21:34 UTC, ievetrov requested changes

2023-06-29 21:34 UTC, ievetrov commented on src/main/kotlin/lesson3/lesson3_task1.kt
> +    println(greetingsUser)
вывод приветствия по заданию стоит сделать в зависимости от времени суток)
получить текущий час можно таким образом `LocalTime.now(Clock.system(ZoneId.systemDefault())).hour`

2023-07-01 02:03 UTC, aandrewkaa commented on src/main/kotlin/lesson3/lesson3_task1.kt
> +    println(greetingsUser)
Исправил

2023-07-01 10:20 UTC, ievetrov approved these changes

2023-07-03 18:25 UTC, ievetrov approved these changes

2023-07-03 22:56 UTC, merged