KS-1-5 solution task5
aandrewkaa/KotlinSprint pull request #5
Opened 2023-06-26 03:17 UTC by aandrewkaa

2023-06-26 18:09 UTC, ievetrov requested changes

2023-06-26 18:09 UTC, ievetrov commented on src/main/kotlin/lesson1/lesson1_task5.kt
> +    println(seconds.toString().padStart(2, '0')+":"+(seconds % 60).toString().padStart(2, '0'))
предлагаю доработать чуть элегантнее.

- используй вместо конкатенации интерполяцию
- попробуй посмотреть как работает String.format() для корректного вывода двух нулей

2023-06-26 23:06 UTC, aandrewkaa commented on src/main/kotlin/lesson1/lesson1_task5.kt
> +    println(seconds.toString().padStart(2, '0')+":"+(seconds % 60).toString().padStart(2, '0'))
поправил

2023-06-27 12:31 UTC, ievetrov approved these changes
все отлично!

2023-06-27 22:04 UTC, merged